// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//! Post-Quantum Cryptography (PQC) Transport Verification Tests.
//!
//! This module verifies that `google-cloud-rust` transports support and negotiate
//! post-quantum hybrid key exchange algorithms (specifically `X25519MLKEM768`,
//! IANA group ID `0x11ec` / 4588) when connecting over TLS 1.3.
//!
//! # Verification Mechanism
//!
//! An isolated instance of `gapic-showcase` is spawned with:
//! * `--tls`: Enables Auto-TLS, generating in-memory CA and server certificates.
//! * `--ca-cert-output-file <path>`: Exports the self-signed CA certificate PEM.
//! * `--tls-groups 0x11ec`: Strictly restricts server-accepted key exchange groups
//!   to `X25519MLKEM768`.
//!
//! If the client's TLS stack (`aws-lc-rs` via `rustls`) does not offer and negotiate
//! `X25519MLKEM768` during the TLS 1.3 `ClientHello`, the server rejects the handshake
//! with a TLS `HandshakeFailure` alert.
//!
//! # Scope of Tests
//!
//! 1. **HTTP/REST Unary (`reqwest`)**: Verifies HTTPS unary RPC execution.
//! 2. **gRPC Streaming (`tonic`)**: Verifies bidirectional streaming RPC execution
//!    over HTTP/2 TLS.

use super::{Anonymous, NeverRetry};
use crate::Result;
use anyhow::Error;
use google_cloud_gax::options::RequestOptionsBuilder;
use google_cloud_gax::retry_policy::{AlwaysRetry, RetryPolicyExt};
use google_cloud_showcase_v1beta1::client::{Echo, Testing};
use google_cloud_showcase_v1beta1::model::EchoRequest;
use std::path::PathBuf;
use std::process::Stdio;
use std::time::Duration;
use tokio::io::{AsyncBufReadExt, BufReader};
use tokio::process::Command;

/// Dedicated port for the PQC Showcase server to prevent collisions with the standard
/// showcase test suite (running concurrently on port `:7469`).
const PQC_PORT: &str = ":7471";
/// Dedicated fallback port to prevent port collisions with the default `:1337`.
const PQC_FALLBACK_PORT: &str = ":1339";
const PQC_ENDPOINT: &str = "https://localhost:7471";

/// Main entry point for the PQC integration test suite.
///
/// Spawns an isolated `gapic-showcase` server configured with Auto-TLS and pinned to
/// `0x11ec` (`X25519MLKEM768`), configures CA trust, and runs transport verifications.
pub async fn run() -> Result<()> {
    let _guard = google_cloud_test_utils::tracing::enable_tracing();

    let path = super::install().await?;
    let showcase: PathBuf = [path.as_str(), "bin", "gapic-showcase"].iter().collect();

    let ca_cert_path =
        std::env::temp_dir().join(format!("showcase_pqc_ca_{}.pem", std::process::id()));
    if ca_cert_path.exists() {
        let _ = std::fs::remove_file(&ca_cert_path);
    }

    let ca_cert_path_str = ca_cert_path
        .to_str()
        .ok_or_else(|| Error::msg("temp dir path is not valid UTF-8"))?;

    tracing::info!("starting {showcase:?} with Auto-TLS (PQC enabled and pinned to 0x11ec)");
    let mut child = Command::new(&showcase)
        .args([
            "run",
            "--port",
            PQC_PORT,
            "--fallback-port",
            PQC_FALLBACK_PORT,
            "--tls",
            "--ca-cert-output-file",
            ca_cert_path_str,
            "--tls-groups",
            "0x11ec", // X25519MLKEM768
        ])
        .stdin(Stdio::null())
        .stdout(Stdio::piped())
        .kill_on_drop(true)
        .spawn()
        .map_err(anyhow::Error::from)?;
    tracing::info!("started showcase PQC server: {child:?}");

    // Wait for Showcase to write the autogenerated CA certificate.
    wait_for_ca_cert(&mut child).await?;
    let _env = scoped_env::ScopedEnv::set("SSL_CERT_FILE", ca_cert_path_str);

    // Wait until the server is ready.
    if let Err(e) = wait_until_ready().await {
        return Err(Error::msg(format!(
            "showcase PQC server is not ready ({child:?}): {e:?}"
        )));
    }

    tracing::info!("testing PQC transport (HTTP unary)");
    test_pqc_http().await?;

    tracing::info!("testing PQC transport (gRPC streaming)");
    test_pqc_grpc().await?;

    Ok(())
}

async fn wait_for_ca_cert(child: &mut tokio::process::Child) -> Result<()> {
    let stdout = child
        .stdout
        .take()
        .ok_or_else(|| Error::msg("failed to capture showcase stdout"))?;
    let mut reader = BufReader::new(stdout).lines();

    let (ca_tx, ca_rx) = tokio::sync::oneshot::channel();
    tokio::spawn(async move {
        let mut ca_tx = Some(ca_tx);
        while let Ok(Some(line)) = reader.next_line().await {
            tracing::debug!("[gapic-showcase] {line}");
            if line.contains("Wrote autogenerated CA certificate to")
                && let Some(tx) = ca_tx.take()
            {
                let _ = tx.send(());
            }
        }
    });

    match tokio::time::timeout(Duration::from_secs(30), ca_rx).await {
        Ok(Ok(())) => Ok(()),
        Ok(Err(_)) => Err(Error::msg(
            "showcase process exited or closed stdout before writing CA certificate",
        )),
        Err(_) => Err(Error::msg(
            "timed out waiting for showcase to write CA certificate within 30s",
        )),
    }
}

async fn wait_until_ready() -> Result<()> {
    let client = Testing::builder()
        .with_endpoint(PQC_ENDPOINT)
        .with_credentials(Anonymous::new().build())
        .with_tracing()
        .build()
        .await?;

    let _list = client
        .list_sessions()
        .with_retry_policy(AlwaysRetry.with_attempt_limit(10))
        .with_attempt_timeout(Duration::from_secs(1))
        .send()
        .await?;
    Ok(())
}

/// Verifies that HTTP unary RPCs (`reqwest`) succeed over a TLS channel requiring `X25519MLKEM768`.
async fn test_pqc_http() -> Result<()> {
    let client = Echo::builder()
        .with_endpoint(PQC_ENDPOINT)
        .with_credentials(Anonymous::new().build())
        .with_retry_policy(NeverRetry)
        .with_tracing()
        .build()
        .await?;

    const TEXT: &str = "testing PQC transport compliance (HTTP unary)";
    let response = client.echo().set_content(TEXT).send().await?;
    assert_eq!(response.content, TEXT);

    tracing::info!("Verified HTTP unary RPC over PQC TLS channel");
    Ok(())
}

/// Verifies that gRPC bidirectional streaming RPCs (`tonic`) succeed over a TLS channel requiring `X25519MLKEM768`.
async fn test_pqc_grpc() -> Result<()> {
    let client = Echo::builder()
        .with_endpoint(PQC_ENDPOINT)
        .with_credentials(Anonymous::new().build())
        .with_retry_policy(NeverRetry)
        .with_tracing()
        .build()
        .await?;

    const TOTAL_MESSAGES: usize = 5;
    let (sender, mut resp_stream) = client.chat().build();

    for i in 0..TOTAL_MESSAGES {
        sender
            .send(EchoRequest::new().set_content(format!("pqc-grpc-msg-{i}")))
            .await?;
    }
    drop(sender);

    let mut received = Vec::new();
    while let Some(res) = resp_stream.next().await {
        received.push(res?.content);
    }

    let expected: Vec<String> = (0..TOTAL_MESSAGES)
        .map(|i| format!("pqc-grpc-msg-{i}"))
        .collect();
    assert_eq!(
        received, expected,
        "gRPC streaming message exchange over PQC TLS channel must match"
    );

    tracing::info!("Verified gRPC streaming over PQC TLS channel (0x11ec)");
    Ok(())
}
