# Copyright 2024 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

options:
  machineType: E2_HIGHCPU_8
  dynamic_substitutions: true
  substitutionOption: 'ALLOW_LOOSE'
  logging: CLOUD_LOGGING_ONLY
  env:
    - GOOGLE_CLOUD_RUST_TEST_RUNNING_ON_GCB=1
    - GOOGLE_CLOUD_PROJECT=${PROJECT_ID}
    - GOOGLE_CLOUD_RUST_TEST_SERVICE_ACCOUNT=rust-sdk-test@${PROJECT_ID}.iam.gserviceaccount.com
    - GOOGLE_CLOUD_RUST_TEST_STORAGE_KMS_RING=us-central1
    - SCCACHE_GCS_BUCKET=${PROJECT_ID}-build-cache
    - SCCACHE_GCS_RW_MODE=READ_WRITE
    - SCCACHE_GCS_KEY_PREFIX=sccache/integration
    - RUSTC_WRAPPER=/workspace/.bin/sccache
    - RUSTFLAGS=${_UNSTABLE_CFG_FLAGS}
    - RUSTDOCFLAGS=${_UNSTABLE_CFG_FLAGS}
serviceAccount: 'projects/${PROJECT_ID}/serviceAccounts/integration-test-runner@${PROJECT_ID}.iam.gserviceaccount.com'
steps:
  - id: 'Set up build cache'
    name: 'gcr.io/cloud-builders/curl'
    entrypoint: bash
    args: ['.gcb/scripts/install-sccache.sh']
    env:
      - _SCCACHE_VERSION=${_SCCACHE_VERSION}
      - _SCCACHE_SHA256=${_SCCACHE_SHA256}
  - id: Run integration tests
    name: 'rust:${_RUST_VERSION}-bookworm'
    script: |
      #!/usr/bin/env bash
      set -e
      cargo test --features run-integration-tests \
        --package integration-tests \
        --package user-guide-samples \
        --package storage-samples \
        --package pubsub-samples
      cargo build --package storage-samples --profile=test --all-features
      cargo build --package pubsub-samples --profile=test --all-features
  - id: Validate default crypto provider behavior
    name: 'rust:${_RUST_VERSION}-bookworm'
    script: |
      #!/usr/bin/env bash
      set -e
      rustup component add clippy
      echo "Verify crypto providers behavior"
      directories=(
        tests/crypto-providers/auth-with-default
        tests/crypto-providers/auth-without-default
        tests/crypto-providers/idtoken-with-default
        tests/crypto-providers/idtoken-with-aws-lc-rs
        tests/crypto-providers/idtoken-with-rust-crypto
        tests/crypto-providers/gaxi-with-default
        tests/crypto-providers/gaxi-with-aws-lc-rs
        tests/crypto-providers/gaxi-with-ring
        tests/crypto-providers/secret-manager-with-default
        tests/crypto-providers/secret-manager-with-aws-lc-rs
        tests/crypto-providers/secret-manager-with-ring
        tests/crypto-providers/storage-with-default
        tests/crypto-providers/storage-with-aws-lc-rs
        tests/crypto-providers/storage-with-ring
      )
      for dir in "${directories[@]}"; do
        echo "Running test in ${dir}"
        # Handle problems updating the `Cargo.lock` files. The first
        # `cargo check` attempt may flake due to network problems. It needs to
        # download data from crates.io and then create the `Cargo.lock` file and
        # (maybe) download some crates. The second attempt should fix most
        # flakes.
        env -C ${dir} cargo check || env -C ${dir} cargo check
        cargo clippy --all-targets --profile=test -- --deny warnings
        env -C ${dir} cargo run
      done

substitutions:
  _RUST_VERSION: '1.92'
  _SCCACHE_VERSION: 'v0.12.0'
  _SCCACHE_SHA256: 'b0e89ead6899224a4ba2b90e9073bf1ce036d95bab30f3dc33c1e1468bc4ad44'
