[package]
name = "gax"
version = "0.1.0"
edition = "2021"

[dependencies]
serde_json = "1.0.132"
types = { version = "0.1.0", path = "../types" }

[dev-dependencies]
reqwest = "0.12.9"
serde = { version = "1.0.214", features = ["serde_derive"] }
serde_with = "3.11.0"
