// Copyright 2025 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// OpenTelemetry Semantic Convention Keys
// See https://opentelemetry.io/docs/specs/semconv/http/http-spans/

pub mod keys {
    /// Span Kind for OpenTelemetry interop.
    ///
    /// Always "Client" for a span representing an outbound HTTP request.
    pub const OTEL_KIND: &str = "otel.kind";
    /// Span Name for OpenTelemetry interop.
    ///
    /// If `url.template` is available use "{http.request.method} {url.template}", otherwise use "{http.request.method}".
    pub const OTEL_NAME: &str = "otel.name";
    /// Span Status Code for OpenTelemetry interop.
    ///
    /// Must be one of "UNSET", "OK", or "ERROR".
    pub const OTEL_STATUS_CODE: &str = "otel.status_code";
    /// Span Status Description for OpenTelemetry interop.
    ///
    /// A human-readable description of the status, used when status_code is "ERROR".
    pub const OTEL_STATUS_DESCRIPTION: &str = "otel.status_description";

    /// The string representation of the gRPC status code.
    #[allow(dead_code)]
    pub const GRPC_STATUS: &str = "grpc.status";

    /// The Remote Procedure Call (RPC) system.
    ///
    /// More information on the OpenTelemetry's
    /// [Remote Procedure Call (RPC) Attributes] page.
    ///
    /// [Remote Procedure Call (RPC) Attributes]: https://github.com/open-telemetry/semantic-conventions/blob/main/docs/registry/attributes/rpc.md#rpc-system-name
    pub const RPC_SYSTEM_NAME: &str = "rpc.system.name";

    /// Status code of the RPC returned by the RPC server or generated by the client.
    ///
    /// More information on the OpenTelemetry's
    /// [Remote Procedure Call (RPC) Attributes] page.
    ///
    /// [Remote Procedure Call (RPC) Attributes]: https://github.com/open-telemetry/semantic-conventions/blob/main/docs/registry/attributes/rpc.md#rpc-response-status-code
    pub const RPC_RESPONSE_STATUS_CODE: &str = "rpc.response.status_code";

    /// The network peer address.
    pub const NETWORK_PEER_ADDRESS: &str = "network.peer.address";
    /// The network peer port.
    pub const NETWORK_PEER_PORT: &str = "network.peer.port";

    // Custom GCP Attributes
    /// The Google Cloud service name.
    ///
    /// Examples: appengine, run, firestore
    pub const GCP_CLIENT_SERVICE: &str = "gcp.client.service";
    /// The client library version.
    ///
    /// Example: v1.0.2
    pub const GCP_CLIENT_VERSION: &str = "gcp.client.version";
    /// The client library repository.
    ///
    /// Always "googleapis/google-cloud-rust".
    pub const GCP_CLIENT_REPO: &str = "gcp.client.repo";
    /// The client library crate name.
    ///
    /// Example: google-cloud-storage
    pub const GCP_CLIENT_ARTIFACT: &str = "gcp.client.artifact";
    /// The Google Cloud resource name.
    ///
    /// Example: //pubsub.googleapis.com/projects/my-project/topics/my-topic
    pub const GCP_RESOURCE_DESTINATION_ID: &str = "gcp.resource.destination.id";
    /// The OpenTelemetry Schema URL indicating the schema used for the telemetry.
    pub const GCP_SCHEMA_URL: &str = "gcp.schema.url";
    /// The number of times this same gRPC request has been resent due to retries.
    ///
    /// 1 for the first retry.
    #[cfg(feature = "_internal-grpc-client")]
    pub const GCP_GRPC_RESEND_COUNT: &str = "gcp.grpc.resend_count";
    /// The Google Cloud error domain.
    ///
    /// Example: pubsub.googleapis.com
    pub const GCP_ERRORS_DOMAIN: &str = "gcp.errors.domain";
    /// A key-value map representing the `ErrorInfo` payload metadata, flattened into a JSON string.
    ///
    /// Example: `{"zone": "us-east1-a", "instance": "instance-1"}`
    pub const GCP_ERRORS_METADATA: &str = "gcp.errors.metadata";

    // Re-export these symbols so we can use them in the `client_request_span!()`
    // macro.
    pub use opentelemetry_semantic_conventions::trace::{
        ERROR_TYPE, HTTP_REQUEST_METHOD, HTTP_REQUEST_RESEND_COUNT, HTTP_RESPONSE_STATUS_CODE,
        RPC_METHOD, SERVER_ADDRESS, SERVER_PORT, URL_FULL,
    };
}

/// Value for [keys::OTEL_KIND].
pub const OTEL_KIND_CLIENT: &str = "Client";
/// Value for `rpc.system`.
#[allow(dead_code)]
pub const RPC_SYSTEM_HTTP: &str = "http";
/// Value for `rpc.system`.
#[cfg(feature = "_internal-grpc-client")]
pub const RPC_SYSTEM_GRPC: &str = "grpc";
/// The GitHub repository hosting the client libraries.
pub const GCP_CLIENT_REPO_GOOGLEAPIS: &str = "googleapis/google-cloud-rust";
/// The OpenTelemetry Schema URL.
pub const SCHEMA_URL_VALUE: &str = "https://opentelemetry.io/schemas/1.39.0";

/// Values for the OpenTelemetry `error.type` attribute.
/// See the semantic conventions around [Error attributes]
///
/// [Error Attributes]: https://opentelemetry.io/docs/specs/semconv/attributes-registry/error/
pub mod error_type_values {
    /// A client-configured timeout was reached.
    pub const CLIENT_TIMEOUT: &str = "CLIENT_TIMEOUT";
    /// The operation was cancelled by the caller.
    #[cfg(feature = "_internal-grpc-client")]
    pub const CLIENT_CANCELLED: &str = "CLIENT_CANCELLED";
    /// Failure to establish the network connection (DNS, TCP, TLS).
    pub const CLIENT_CONNECTION_ERROR: &str = "CLIENT_CONNECTION_ERROR";
    /// Client-side issue forming or sending the request.
    pub const CLIENT_REQUEST_ERROR: &str = "CLIENT_REQUEST_ERROR";
    /// Client-side error decoding the response body.
    pub const CLIENT_RESPONSE_DECODE_ERROR: &str = "CLIENT_RESPONSE_DECODE_ERROR";
    /// Error during credential acquisition or application.
    pub const CLIENT_AUTHENTICATION_ERROR: &str = "CLIENT_AUTHENTICATION_ERROR";
    /// Resource exhausted (e.g. retry limit reached).
    pub const CLIENT_RETRY_EXHAUSTED: &str = "CLIENT_RETRY_EXHAUSTED";
    /// Unknown error type.
    pub const UNKNOWN: &str = "UNKNOWN";
}

// There is no OK constant because in practice an instrumented library should never use it.
/// Values for the OpenTelemetry `otel.status_code` attribute.
pub mod otel_status_codes {
    /// The operation contains an error.
    pub const ERROR: &str = "ERROR";
    /// The default status.
    pub const UNSET: &str = "UNSET";
}
