// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// Code generated by sidekick. DO NOT EDIT.

#![allow(missing_docs)]

//! End-to-end mocks for the `google.cloud.bigquery.storage.v1.BigQueryWrite` gRPC service.
//!
//! Use this crate for end-to-end client library tests. Start a local server
//! implementing the `google.cloud.bigquery.storage.v1.BigQueryWrite` API, with the implementation
//! defined by a mock. Then test the client library against this mock.
//!
//! # Example
//! ```no_rust
//! use bigquery_grpc_mock::{start, MockBigQueryWrite};
//! use google_cloud_big_query_write::client::BigQueryWrite;
//! use google_cloud_auth::credentials::anonymous::Builder as Anonymous;
//!
//! # async fn test() -> anyhow::Result<()> {
//! let mut mock = MockBigQueryWrite::new();
//! mock.expect_get_write_stream()
//!     .return_once(|_| Err(tonic::Status::invalid_argument("test message")));
//! // Starts a service using `mock` and a random port.
//! let (endpoint, server) = start("0.0.0.0:0", mock).await?;
//! // Use the service in a test.
//! let client = BigQueryWrite::builder()
//!     .with_endpoint(endpoint)
//!     .with_credentials(Anonymous::default().build())
//!     .build()
//!     .await?;
//! let err = client
//!     .get_write_stream()
//!     .send()
//!     .unwrap_err("mock returns an error");
//! assert_eq!(err.status().is_some(), "{err:?}");
//! # Ok(()) }
//! ```

mod mocks;
use std::net::SocketAddr;
use tokio::task::JoinHandle;

/// A mock for the `google.cloud.bigquery.storage.v1.BigQueryWrite` gRPC service.
///
/// # Example
/// ```no_rust
/// use bigquery_grpc_mock::MockBigQueryWrite;
/// let mut mock = MockBigQueryWrite::new();
/// let (tx, rx) = tokio::sync::mpsc::channel(128);
/// mock.expect_streaming_rpc() // Made up bidirectional streaming RPC.
///     .return_once(|_request| Ok(tonic::Response::from(rx)));
/// // use `tx` to mock streaming responses.
/// ```
pub use mocks::MockBigQueryWrite;

/// Starts a mock `google.cloud.bigquery.storage.v1.BigQueryWrite` gRPC service.
///
/// # Example
/// ```
/// use bigquery_grpc_mock::{start, MockBigQueryWrite};
/// # async fn test() -> anyhow::Result<()> {
/// let mut mock = MockBigQueryWrite::new();
/// mock.expect_get_write_stream()
///     .return_once(|_| Err(tonic::Status::invalid_argument("test message")));
/// // starts a service using `mock` and a random port.
/// let (address, server) = start("0.0.0.0:0", mock).await?;
/// // ... ... test goes here ... ...
/// # Ok(()) }
/// ```
pub async fn start<T>(address: &str, service: T) -> anyhow::Result<(String, JoinHandle<()>)>
where
    T: google::cloud::bigquery::storage::v1::big_query_write_server::BigQueryWrite,
{
    let listener = tokio::net::TcpListener::bind(address).await?;
    let addr = listener.local_addr()?;

    let server = tokio::spawn(async {
        let stream = tokio_stream::wrappers::TcpListenerStream::new(listener);

        let _ = tonic::transport::Server::builder()
            .add_service(google::cloud::bigquery::storage::v1::big_query_write_server::BigQueryWriteServer::new(
                service,
            ))
            .serve_with_incoming(stream)
            .await;
    });

    Ok((to_uri(addr), server))
}

// This function is public only for the sake of unit testing
pub fn to_uri(addr: SocketAddr) -> String {
    if addr.is_ipv6() {
        format!("http://[{}]:{}", addr.ip(), addr.port())
    } else {
        format!("http://{}:{}", addr.ip(), addr.port())
    }
}

include!("generated/protos/includes.rs");
