// This file is @generated by prost-build.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ArrowSchema {
    #[prost(bytes = "bytes", tag = "1")]
    pub serialized_schema: ::prost::bytes::Bytes,
}
impl ::prost::Name for ArrowSchema {
    const NAME: &'static str = "ArrowSchema";
    const PACKAGE: &'static str = "google.cloud.bigquery.storage.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "google.cloud.bigquery.storage.v1.ArrowSchema".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "type.googleapis.com/google.cloud.bigquery.storage.v1.ArrowSchema".into()
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ArrowRecordBatch {
    #[prost(bytes = "bytes", tag = "1")]
    pub serialized_record_batch: ::prost::bytes::Bytes,
    #[deprecated]
    #[prost(int64, tag = "2")]
    pub row_count: i64,
}
impl ::prost::Name for ArrowRecordBatch {
    const NAME: &'static str = "ArrowRecordBatch";
    const PACKAGE: &'static str = "google.cloud.bigquery.storage.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "google.cloud.bigquery.storage.v1.ArrowRecordBatch".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "type.googleapis.com/google.cloud.bigquery.storage.v1.ArrowRecordBatch".into()
    }
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ArrowSerializationOptions {
    #[prost(enumeration = "arrow_serialization_options::CompressionCodec", tag = "2")]
    pub buffer_compression: i32,
    #[prost(
        enumeration = "arrow_serialization_options::PicosTimestampPrecision",
        tag = "3"
    )]
    pub picos_timestamp_precision: i32,
}
/// Nested message and enum types in `ArrowSerializationOptions`.
pub mod arrow_serialization_options {
    #[derive(
        Clone,
        Copy,
        Debug,
        PartialEq,
        Eq,
        Hash,
        PartialOrd,
        Ord,
        ::prost::Enumeration
    )]
    #[repr(i32)]
    pub enum CompressionCodec {
        CompressionUnspecified = 0,
        Lz4Frame = 1,
        Zstd = 2,
    }
    impl CompressionCodec {
        /// String value of the enum field names used in the ProtoBuf definition.
        ///
        /// The values are not transformed in any way and thus are considered stable
        /// (if the ProtoBuf definition does not change) and safe for programmatic use.
        pub fn as_str_name(&self) -> &'static str {
            match self {
                Self::CompressionUnspecified => "COMPRESSION_UNSPECIFIED",
                Self::Lz4Frame => "LZ4_FRAME",
                Self::Zstd => "ZSTD",
            }
        }
        /// Creates an enum from field names used in the ProtoBuf definition.
        pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
            match value {
                "COMPRESSION_UNSPECIFIED" => Some(Self::CompressionUnspecified),
                "LZ4_FRAME" => Some(Self::Lz4Frame),
                "ZSTD" => Some(Self::Zstd),
                _ => None,
            }
        }
    }
    #[derive(
        Clone,
        Copy,
        Debug,
        PartialEq,
        Eq,
        Hash,
        PartialOrd,
        Ord,
        ::prost::Enumeration
    )]
    #[repr(i32)]
    pub enum PicosTimestampPrecision {
        Unspecified = 0,
        TimestampPrecisionMicros = 1,
        TimestampPrecisionNanos = 2,
        TimestampPrecisionPicos = 3,
    }
    impl PicosTimestampPrecision {
        /// String value of the enum field names used in the ProtoBuf definition.
        ///
        /// The values are not transformed in any way and thus are considered stable
        /// (if the ProtoBuf definition does not change) and safe for programmatic use.
        pub fn as_str_name(&self) -> &'static str {
            match self {
                Self::Unspecified => "PICOS_TIMESTAMP_PRECISION_UNSPECIFIED",
                Self::TimestampPrecisionMicros => "TIMESTAMP_PRECISION_MICROS",
                Self::TimestampPrecisionNanos => "TIMESTAMP_PRECISION_NANOS",
                Self::TimestampPrecisionPicos => "TIMESTAMP_PRECISION_PICOS",
            }
        }
        /// Creates an enum from field names used in the ProtoBuf definition.
        pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
            match value {
                "PICOS_TIMESTAMP_PRECISION_UNSPECIFIED" => Some(Self::Unspecified),
                "TIMESTAMP_PRECISION_MICROS" => Some(Self::TimestampPrecisionMicros),
                "TIMESTAMP_PRECISION_NANOS" => Some(Self::TimestampPrecisionNanos),
                "TIMESTAMP_PRECISION_PICOS" => Some(Self::TimestampPrecisionPicos),
                _ => None,
            }
        }
    }
}
impl ::prost::Name for ArrowSerializationOptions {
    const NAME: &'static str = "ArrowSerializationOptions";
    const PACKAGE: &'static str = "google.cloud.bigquery.storage.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "google.cloud.bigquery.storage.v1.ArrowSerializationOptions".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "type.googleapis.com/google.cloud.bigquery.storage.v1.ArrowSerializationOptions"
            .into()
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct AvroSchema {
    #[prost(string, tag = "1")]
    pub schema: ::prost::alloc::string::String,
}
impl ::prost::Name for AvroSchema {
    const NAME: &'static str = "AvroSchema";
    const PACKAGE: &'static str = "google.cloud.bigquery.storage.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "google.cloud.bigquery.storage.v1.AvroSchema".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "type.googleapis.com/google.cloud.bigquery.storage.v1.AvroSchema".into()
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct AvroRows {
    #[prost(bytes = "bytes", tag = "1")]
    pub serialized_binary_rows: ::prost::bytes::Bytes,
    #[deprecated]
    #[prost(int64, tag = "2")]
    pub row_count: i64,
}
impl ::prost::Name for AvroRows {
    const NAME: &'static str = "AvroRows";
    const PACKAGE: &'static str = "google.cloud.bigquery.storage.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "google.cloud.bigquery.storage.v1.AvroRows".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "type.googleapis.com/google.cloud.bigquery.storage.v1.AvroRows".into()
    }
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct AvroSerializationOptions {
    #[prost(bool, tag = "1")]
    pub enable_display_name_attribute: bool,
    #[prost(
        enumeration = "avro_serialization_options::PicosTimestampPrecision",
        tag = "2"
    )]
    pub picos_timestamp_precision: i32,
}
/// Nested message and enum types in `AvroSerializationOptions`.
pub mod avro_serialization_options {
    #[derive(
        Clone,
        Copy,
        Debug,
        PartialEq,
        Eq,
        Hash,
        PartialOrd,
        Ord,
        ::prost::Enumeration
    )]
    #[repr(i32)]
    pub enum PicosTimestampPrecision {
        Unspecified = 0,
        TimestampPrecisionMicros = 1,
        TimestampPrecisionNanos = 2,
        TimestampPrecisionPicos = 3,
    }
    impl PicosTimestampPrecision {
        /// String value of the enum field names used in the ProtoBuf definition.
        ///
        /// The values are not transformed in any way and thus are considered stable
        /// (if the ProtoBuf definition does not change) and safe for programmatic use.
        pub fn as_str_name(&self) -> &'static str {
            match self {
                Self::Unspecified => "PICOS_TIMESTAMP_PRECISION_UNSPECIFIED",
                Self::TimestampPrecisionMicros => "TIMESTAMP_PRECISION_MICROS",
                Self::TimestampPrecisionNanos => "TIMESTAMP_PRECISION_NANOS",
                Self::TimestampPrecisionPicos => "TIMESTAMP_PRECISION_PICOS",
            }
        }
        /// Creates an enum from field names used in the ProtoBuf definition.
        pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
            match value {
                "PICOS_TIMESTAMP_PRECISION_UNSPECIFIED" => Some(Self::Unspecified),
                "TIMESTAMP_PRECISION_MICROS" => Some(Self::TimestampPrecisionMicros),
                "TIMESTAMP_PRECISION_NANOS" => Some(Self::TimestampPrecisionNanos),
                "TIMESTAMP_PRECISION_PICOS" => Some(Self::TimestampPrecisionPicos),
                _ => None,
            }
        }
    }
}
impl ::prost::Name for AvroSerializationOptions {
    const NAME: &'static str = "AvroSerializationOptions";
    const PACKAGE: &'static str = "google.cloud.bigquery.storage.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "google.cloud.bigquery.storage.v1.AvroSerializationOptions".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "type.googleapis.com/google.cloud.bigquery.storage.v1.AvroSerializationOptions"
            .into()
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ReadSession {
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "2")]
    pub expire_time: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(enumeration = "DataFormat", tag = "3")]
    pub data_format: i32,
    #[prost(string, tag = "6")]
    pub table: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "7")]
    pub table_modifiers: ::core::option::Option<read_session::TableModifiers>,
    #[prost(message, optional, tag = "8")]
    pub read_options: ::core::option::Option<read_session::TableReadOptions>,
    #[prost(message, repeated, tag = "10")]
    pub streams: ::prost::alloc::vec::Vec<ReadStream>,
    #[prost(int64, tag = "12")]
    pub estimated_total_bytes_scanned: i64,
    #[prost(int64, tag = "15")]
    pub estimated_total_physical_file_size: i64,
    #[prost(int64, tag = "14")]
    pub estimated_row_count: i64,
    #[prost(string, tag = "13")]
    pub trace_id: ::prost::alloc::string::String,
    #[prost(oneof = "read_session::Schema", tags = "4, 5")]
    pub schema: ::core::option::Option<read_session::Schema>,
}
/// Nested message and enum types in `ReadSession`.
pub mod read_session {
    #[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
    pub struct TableModifiers {
        #[prost(message, optional, tag = "1")]
        pub snapshot_time: ::core::option::Option<::prost_types::Timestamp>,
    }
    impl ::prost::Name for TableModifiers {
        const NAME: &'static str = "TableModifiers";
        const PACKAGE: &'static str = "google.cloud.bigquery.storage.v1";
        fn full_name() -> ::prost::alloc::string::String {
            "google.cloud.bigquery.storage.v1.ReadSession.TableModifiers".into()
        }
        fn type_url() -> ::prost::alloc::string::String {
            "type.googleapis.com/google.cloud.bigquery.storage.v1.ReadSession.TableModifiers"
                .into()
        }
    }
    #[derive(Clone, PartialEq, ::prost::Message)]
    pub struct TableReadOptions {
        #[prost(string, repeated, tag = "1")]
        pub selected_fields: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
        #[prost(string, tag = "2")]
        pub row_restriction: ::prost::alloc::string::String,
        #[prost(double, optional, tag = "5")]
        pub sample_percentage: ::core::option::Option<f64>,
        #[prost(
            enumeration = "table_read_options::ResponseCompressionCodec",
            optional,
            tag = "6"
        )]
        pub response_compression_codec: ::core::option::Option<i32>,
        #[prost(
            oneof = "table_read_options::OutputFormatSerializationOptions",
            tags = "3, 4"
        )]
        pub output_format_serialization_options: ::core::option::Option<
            table_read_options::OutputFormatSerializationOptions,
        >,
    }
    /// Nested message and enum types in `TableReadOptions`.
    pub mod table_read_options {
        #[derive(
            Clone,
            Copy,
            Debug,
            PartialEq,
            Eq,
            Hash,
            PartialOrd,
            Ord,
            ::prost::Enumeration
        )]
        #[repr(i32)]
        pub enum ResponseCompressionCodec {
            Unspecified = 0,
            Lz4 = 2,
        }
        impl ResponseCompressionCodec {
            /// String value of the enum field names used in the ProtoBuf definition.
            ///
            /// The values are not transformed in any way and thus are considered stable
            /// (if the ProtoBuf definition does not change) and safe for programmatic use.
            pub fn as_str_name(&self) -> &'static str {
                match self {
                    Self::Unspecified => "RESPONSE_COMPRESSION_CODEC_UNSPECIFIED",
                    Self::Lz4 => "RESPONSE_COMPRESSION_CODEC_LZ4",
                }
            }
            /// Creates an enum from field names used in the ProtoBuf definition.
            pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
                match value {
                    "RESPONSE_COMPRESSION_CODEC_UNSPECIFIED" => Some(Self::Unspecified),
                    "RESPONSE_COMPRESSION_CODEC_LZ4" => Some(Self::Lz4),
                    _ => None,
                }
            }
        }
        #[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Oneof)]
        pub enum OutputFormatSerializationOptions {
            #[prost(message, tag = "3")]
            ArrowSerializationOptions(super::super::ArrowSerializationOptions),
            #[prost(message, tag = "4")]
            AvroSerializationOptions(super::super::AvroSerializationOptions),
        }
    }
    impl ::prost::Name for TableReadOptions {
        const NAME: &'static str = "TableReadOptions";
        const PACKAGE: &'static str = "google.cloud.bigquery.storage.v1";
        fn full_name() -> ::prost::alloc::string::String {
            "google.cloud.bigquery.storage.v1.ReadSession.TableReadOptions".into()
        }
        fn type_url() -> ::prost::alloc::string::String {
            "type.googleapis.com/google.cloud.bigquery.storage.v1.ReadSession.TableReadOptions"
                .into()
        }
    }
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum Schema {
        #[prost(message, tag = "4")]
        AvroSchema(super::AvroSchema),
        #[prost(message, tag = "5")]
        ArrowSchema(super::ArrowSchema),
    }
}
impl ::prost::Name for ReadSession {
    const NAME: &'static str = "ReadSession";
    const PACKAGE: &'static str = "google.cloud.bigquery.storage.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "google.cloud.bigquery.storage.v1.ReadSession".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "type.googleapis.com/google.cloud.bigquery.storage.v1.ReadSession".into()
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ReadStream {
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
}
impl ::prost::Name for ReadStream {
    const NAME: &'static str = "ReadStream";
    const PACKAGE: &'static str = "google.cloud.bigquery.storage.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "google.cloud.bigquery.storage.v1.ReadStream".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "type.googleapis.com/google.cloud.bigquery.storage.v1.ReadStream".into()
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum DataFormat {
    Unspecified = 0,
    Avro = 1,
    Arrow = 2,
}
impl DataFormat {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "DATA_FORMAT_UNSPECIFIED",
            Self::Avro => "AVRO",
            Self::Arrow => "ARROW",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "DATA_FORMAT_UNSPECIFIED" => Some(Self::Unspecified),
            "AVRO" => Some(Self::Avro),
            "ARROW" => Some(Self::Arrow),
            _ => None,
        }
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CreateReadSessionRequest {
    #[prost(string, tag = "1")]
    pub parent: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "2")]
    pub read_session: ::core::option::Option<ReadSession>,
    #[prost(int32, tag = "3")]
    pub max_stream_count: i32,
    #[prost(int32, tag = "4")]
    pub preferred_min_stream_count: i32,
}
impl ::prost::Name for CreateReadSessionRequest {
    const NAME: &'static str = "CreateReadSessionRequest";
    const PACKAGE: &'static str = "google.cloud.bigquery.storage.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "google.cloud.bigquery.storage.v1.CreateReadSessionRequest".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "type.googleapis.com/google.cloud.bigquery.storage.v1.CreateReadSessionRequest"
            .into()
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ReadRowsRequest {
    #[prost(string, tag = "1")]
    pub read_stream: ::prost::alloc::string::String,
    #[prost(int64, tag = "2")]
    pub offset: i64,
    #[prost(oneof = "read_rows_request::OutputFormatSerializationOptions", tags = "5")]
    pub output_format_serialization_options: ::core::option::Option<
        read_rows_request::OutputFormatSerializationOptions,
    >,
}
/// Nested message and enum types in `ReadRowsRequest`.
pub mod read_rows_request {
    #[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum OutputFormatSerializationOptions {
        #[prost(message, tag = "5")]
        ArrowSerializationOptions(super::ArrowSerializationOptions),
    }
}
impl ::prost::Name for ReadRowsRequest {
    const NAME: &'static str = "ReadRowsRequest";
    const PACKAGE: &'static str = "google.cloud.bigquery.storage.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "google.cloud.bigquery.storage.v1.ReadRowsRequest".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "type.googleapis.com/google.cloud.bigquery.storage.v1.ReadRowsRequest".into()
    }
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ThrottleState {
    #[prost(int32, tag = "1")]
    pub throttle_percent: i32,
}
impl ::prost::Name for ThrottleState {
    const NAME: &'static str = "ThrottleState";
    const PACKAGE: &'static str = "google.cloud.bigquery.storage.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "google.cloud.bigquery.storage.v1.ThrottleState".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "type.googleapis.com/google.cloud.bigquery.storage.v1.ThrottleState".into()
    }
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct StreamStats {
    #[prost(message, optional, tag = "2")]
    pub progress: ::core::option::Option<stream_stats::Progress>,
}
/// Nested message and enum types in `StreamStats`.
pub mod stream_stats {
    #[derive(Clone, Copy, PartialEq, ::prost::Message)]
    pub struct Progress {
        #[prost(double, tag = "1")]
        pub at_response_start: f64,
        #[prost(double, tag = "2")]
        pub at_response_end: f64,
    }
    impl ::prost::Name for Progress {
        const NAME: &'static str = "Progress";
        const PACKAGE: &'static str = "google.cloud.bigquery.storage.v1";
        fn full_name() -> ::prost::alloc::string::String {
            "google.cloud.bigquery.storage.v1.StreamStats.Progress".into()
        }
        fn type_url() -> ::prost::alloc::string::String {
            "type.googleapis.com/google.cloud.bigquery.storage.v1.StreamStats.Progress"
                .into()
        }
    }
}
impl ::prost::Name for StreamStats {
    const NAME: &'static str = "StreamStats";
    const PACKAGE: &'static str = "google.cloud.bigquery.storage.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "google.cloud.bigquery.storage.v1.StreamStats".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "type.googleapis.com/google.cloud.bigquery.storage.v1.StreamStats".into()
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ReadRowsResponse {
    #[prost(int64, tag = "6")]
    pub row_count: i64,
    #[prost(message, optional, tag = "2")]
    pub stats: ::core::option::Option<StreamStats>,
    #[prost(message, optional, tag = "5")]
    pub throttle_state: ::core::option::Option<ThrottleState>,
    #[prost(int64, optional, tag = "9")]
    pub uncompressed_byte_size: ::core::option::Option<i64>,
    #[prost(int64, optional, tag = "10")]
    pub total_estimated_row_count: ::core::option::Option<i64>,
    #[prost(oneof = "read_rows_response::Rows", tags = "3, 4")]
    pub rows: ::core::option::Option<read_rows_response::Rows>,
    #[prost(oneof = "read_rows_response::Schema", tags = "7, 8")]
    pub schema: ::core::option::Option<read_rows_response::Schema>,
}
/// Nested message and enum types in `ReadRowsResponse`.
pub mod read_rows_response {
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum Rows {
        #[prost(message, tag = "3")]
        AvroRows(super::AvroRows),
        #[prost(message, tag = "4")]
        ArrowRecordBatch(super::ArrowRecordBatch),
    }
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum Schema {
        #[prost(message, tag = "7")]
        AvroSchema(super::AvroSchema),
        #[prost(message, tag = "8")]
        ArrowSchema(super::ArrowSchema),
    }
}
impl ::prost::Name for ReadRowsResponse {
    const NAME: &'static str = "ReadRowsResponse";
    const PACKAGE: &'static str = "google.cloud.bigquery.storage.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "google.cloud.bigquery.storage.v1.ReadRowsResponse".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "type.googleapis.com/google.cloud.bigquery.storage.v1.ReadRowsResponse".into()
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SplitReadStreamRequest {
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    #[prost(double, tag = "2")]
    pub fraction: f64,
}
impl ::prost::Name for SplitReadStreamRequest {
    const NAME: &'static str = "SplitReadStreamRequest";
    const PACKAGE: &'static str = "google.cloud.bigquery.storage.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "google.cloud.bigquery.storage.v1.SplitReadStreamRequest".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "type.googleapis.com/google.cloud.bigquery.storage.v1.SplitReadStreamRequest"
            .into()
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SplitReadStreamResponse {
    #[prost(message, optional, tag = "1")]
    pub primary_stream: ::core::option::Option<ReadStream>,
    #[prost(message, optional, tag = "2")]
    pub remainder_stream: ::core::option::Option<ReadStream>,
}
impl ::prost::Name for SplitReadStreamResponse {
    const NAME: &'static str = "SplitReadStreamResponse";
    const PACKAGE: &'static str = "google.cloud.bigquery.storage.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "google.cloud.bigquery.storage.v1.SplitReadStreamResponse".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "type.googleapis.com/google.cloud.bigquery.storage.v1.SplitReadStreamResponse"
            .into()
    }
}
