// This file is @generated by prost-build.
pub mod google {
    pub mod cloud {
        pub mod bigquery {
            pub mod storage {
                pub mod v1 {
                    include!("google.cloud.bigquery.storage.v1.rs");
            include!("../convert.rs");
                }
            }
        }
    }
}
