# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

[general]
specification-source = 'google/cloud/asset/v1'
service-config = 'google/cloud/asset/v1/cloudasset_v1.yaml'

[codec]
copyright-year = '2025'
'package:accesscontextmanager_v1' = 'package=google-cloud-identity-accesscontextmanager-v1,source=google.identity.accesscontextmanager.v1,path=src/generated/identity/accesscontextmanager/v1,version=0.1'
'package:orgpolicy_v1' = 'package=google-cloud-orgpolicy-v1,source=google.cloud.orgpolicy.v1,path=src/generated/cloud/orgpolicy/v1,version=0.1'
'package:osconfig_v1' = 'package=google-cloud-osconfig-v1,source=google.cloud.osconfig.v1,path=src/generated/cloud/osconfig/v1,version=0.1'
