// Copyright 2025 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package dart

import (
	"fmt"
	"strings"

	"github.com/googleapis/google-cloud-rust/generator/internal/api"
	"github.com/googleapis/google-cloud-rust/generator/internal/language"
	"github.com/googleapis/google-cloud-rust/generator/internal/license"
	"github.com/iancoleman/strcase"
)

type modelAnnotations struct {
	// The Dart package name (e.g. google_cloud_secretmanager).
	PackageName string
	// Name of the API in snake_format (e.g. secretmanager).
	MainFileName      string
	SourcePackageName string
	HasServices       bool
	CopyrightYear     string
	BoilerPlate       []string
	DefaultHost       string
	DocLines          []string
}

type serviceAnnotations struct {
	// The service name using Dart naming conventions.
	Name        string
	DocLines    []string
	FieldName   string
	StructName  string
	DefaultHost string
}

type messageAnnotation struct {
	Name           string
	DocLines       []string
	QualifiedName  string
	HasNestedTypes bool
	// The FQN is the source specification
	SourceFQN   string
	BasicFields []*api.Field
}

type methodAnnotation struct {
	// The method name using Dart naming conventions.
	Name         string
	RequestType  string
	ResponseType string
	DocLines     []string
	PathParams   []*api.Field
	QueryParams  []*api.Field
	BodyAccessor string
}

type pathInfoAnnotation struct {
	Method      string
	PathFmt     string
	PathArgs    []string
	HasPathArgs bool
	HasBody     bool
}

type oneOfAnnotation struct {
	Name     string
	DocLines []string
}

type fieldAnnotation struct {
	Name             string
	Type             string
	DocLines         []string
	AsQueryParameter string
}

type enumAnnotation struct {
	Name     string
	DocLines []string
}

type enumValueAnnotation struct {
	Name     string
	DocLines []string
}

// annotateModel creates a struct used as input for Mustache templates.
// Fields and methods defined in this struct directly correspond to Mustache
// tags. For example, the Mustache tag {{#Services}} uses the
// [Template.Services] field.
func annotateModel(model *api.API, options map[string]string) (*modelAnnotations, error) {
	var (
		packageNameOverride string
		generationYear      string
	)

	for key, definition := range options {
		switch {
		case key == "package-name-override":
			packageNameOverride = definition
		case key == "copyright-year":
			generationYear = definition
		case strings.HasPrefix(key, "import-mapping"):
			keys := strings.Split(key, ":")
			if len(keys) != 2 {
				return nil, fmt.Errorf("key should be in the format import-mapping:proto.path, got=%q", key)
			}
			defs := strings.Split(definition, ";")
			if len(defs) != 2 {
				return nil, fmt.Errorf("%s should be in the format path;name, got=%q", definition, keys[1])
			}
			// TODO(#1034): Handle updating Dart imports.
		}
	}

	loadWellKnownTypes(model.State)
	for _, e := range model.State.EnumByID {
		annotateEnum(e, model.State)
	}
	for _, m := range model.State.MessageByID {
		annotateMessage(m, model.State)
	}
	for _, s := range model.Services {
		annotateService(s, model.State)
	}
	ann := &modelAnnotations{
		PackageName:   modelPackageName(model, packageNameOverride),
		MainFileName:  strcase.ToSnake(model.Name),
		HasServices:   len(model.Services) > 0,
		CopyrightYear: generationYear,
		BoilerPlate: append(license.LicenseHeaderBulk(),
			"",
			" Code generated by sidekick. DO NOT EDIT."),
		DefaultHost: func() string {
			if len(model.Services) > 0 {
				return model.Services[0].DefaultHost
			}
			return ""
		}(),
		DocLines: formatDocComments(model.Description, model.State),
	}

	model.Codec = ann
	return ann, nil
}

func annotateService(s *api.Service, state *api.APIState) {
	// Some methods are skipped.
	methods := language.FilterSlice(s.Methods, func(m *api.Method) bool {
		return generateMethod(m)
	})
	for _, m := range methods {
		annotateMethod(m, state)
	}
	ann := &serviceAnnotations{
		Name:        s.Name,
		DocLines:    formatDocComments(s.Documentation, state),
		FieldName:   strcase.ToLowerCamel(s.Name),
		StructName:  s.Name,
		DefaultHost: s.DefaultHost,
	}
	s.Codec = ann
}

func annotateMessage(m *api.Message, state *api.APIState) {
	for _, f := range m.Fields {
		annotateField(f, state)
	}
	for _, f := range m.OneOfs {
		annotateOneOf(f, state)
	}
	m.Codec = &messageAnnotation{
		Name:           messageName(m),
		DocLines:       formatDocComments(m.Documentation, state),
		QualifiedName:  messageName(m),
		HasNestedTypes: language.HasNestedTypes(m),
		SourceFQN:      strings.TrimPrefix(m.ID, "."),
		BasicFields: language.FilterSlice(m.Fields, func(s *api.Field) bool {
			return !s.IsOneOf
		}),
	}
}

func annotateMethod(m *api.Method, state *api.APIState) {
	pathInfoAnnotation := &pathInfoAnnotation{
		Method:   m.PathInfo.Verb,
		PathFmt:  httpPathFmt(m.PathInfo),
		PathArgs: httpPathArgs(m.PathInfo),
		HasBody:  m.PathInfo.BodyFieldPath != "",
	}
	m.PathInfo.Codec = pathInfoAnnotation
	annotation := &methodAnnotation{
		Name:         strcase.ToLowerCamel(m.Name),
		RequestType:  methodInOutTypeName(m.InputTypeID, state),
		ResponseType: methodInOutTypeName(m.OutputTypeID, state),
		DocLines:     formatDocComments(m.Documentation, state),
		BodyAccessor: bodyAccessor(m),
		PathParams:   language.PathParams(m, state),
		QueryParams:  language.QueryParams(m, state),
	}
	m.Codec = annotation
}

func annotateOneOf(field *api.OneOf, state *api.APIState) {
	field.Codec = &oneOfAnnotation{
		Name:     strcase.ToLowerCamel(field.Name),
		DocLines: formatDocComments(field.Documentation, state),
	}
}

func annotateField(field *api.Field, state *api.APIState) {
	field.Codec = &fieldAnnotation{
		Name:     strcase.ToLowerCamel(field.Name),
		Type:     fieldType(field, state),
		DocLines: formatDocComments(field.Documentation, state),
	}
}

func annotateEnum(e *api.Enum, state *api.APIState) {
	for _, ev := range e.Values {
		annotateEnumValue(ev, state)
	}
	e.Codec = &enumAnnotation{
		Name:     enumName(e),
		DocLines: formatDocComments(e.Documentation, state),
	}
}

func annotateEnumValue(ev *api.EnumValue, state *api.APIState) {
	ev.Codec = &enumValueAnnotation{
		Name:     enumValueName(ev),
		DocLines: formatDocComments(ev.Documentation, state),
	}
}
