// Copyright 2024 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//! Common errors generated by the components in this crate.

use crate::io::HttpResponse;
use std::error::Error;

pub use google_cloud_gax::error::CredentialsError;

/// Represents an error using [SubjectTokenProvider].
///
/// The Google Cloud client libraries may experience problems when
/// fetching the subject token. For example, a temporary error may occur
/// when [SubjectTokenProvider] tries to fetch the token from a third party service.
///
/// Applications rarely need to create instances of this error type. The
/// exception may be when they are providing their own custom [SubjectTokenProvider]
/// implementation.
///
/// # Example
///
/// ```
/// # use std::error::Error;
/// # use std::fmt;
/// # use google_cloud_auth::errors::SubjectTokenProviderError;
/// #[derive(Debug)]
/// struct CustomTokenError {
///     message: String,
///     is_transient: bool,
/// }
///
/// impl fmt::Display for CustomTokenError {
///     fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
///         write!(f, "{}", self.message)
///     }
/// }
///
/// impl Error for CustomTokenError {}
///
/// impl SubjectTokenProviderError for CustomTokenError {
///     fn is_transient(&self) -> bool {
///         self.is_transient
///     }
/// }
/// ```
/// [SubjectTokenProvider]: crate::credentials::subject_token::SubjectTokenProvider
pub trait SubjectTokenProviderError: Error + Send + Sync + 'static {
    /// Return true if the error is transient and the call may succeed in the future.
    ///
    /// Applications should only return true if the error automatically
    /// recovers, without the need for any human action.
    ///
    /// Timeouts and network problems are good candidates for `is_transient() == true`.
    /// Configuration errors that require changing a file, or installing an executable are not.
    fn is_transient(&self) -> bool;
}

impl SubjectTokenProviderError for CredentialsError {
    fn is_transient(&self) -> bool {
        self.is_transient()
    }
}

/// Wraps a `Box<dyn Error>` from an I/O provider (e.g. `HttpClientProvider`)
/// so it can be used as a source in `CredentialsError::from_source` (which
/// requires `Error + Sized`).
#[derive(Debug)]
struct TransportError {
    message: String,
    source: Box<dyn Error + Send + Sync>,
}

impl std::fmt::Display for TransportError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "{}", self.message)
    }
}

impl Error for TransportError {
    fn source(&self) -> Option<&(dyn Error + 'static)> {
        Some(self.source.as_ref())
    }
}

/// Creates a `CredentialsError` from a failed HTTP provider call.
///
/// Use this when `HttpClientProvider::execute()` returns `Err(...)`,
/// meaning the request failed at the transport level (connection refused,
/// timeout, DNS resolution, TLS handshake, etc.) and no HTTP response was
/// received. These errors are marked as transient because transport-level
/// failures are typically recoverable. Non-transient cases (e.g.,
/// misconfigured endpoints) will be bounded by the caller's retry policy.
///
/// For errors from a received HTTP response (non-2xx status), use
/// [`from_http_response`] instead, which checks the status code to
/// determine retryability.
pub(crate) fn from_http_error(source: Box<dyn Error + Send + Sync>, msg: &str) -> CredentialsError {
    CredentialsError::from_source(
        true,
        TransportError {
            message: msg.to_string(),
            source,
        },
    )
}

/// Creates a `CredentialsError` from a non-success HTTP response.
///
/// Use this when `HttpClientProvider::execute()` returns `Ok(response)`
/// but `response.is_success()` is false.
pub(crate) fn from_http_response(response: &HttpResponse, msg: &str) -> CredentialsError {
    let status = response.status;
    let body = String::from_utf8_lossy(&response.body);
    CredentialsError::from_msg(
        response.is_retryable(),
        format!("{msg}, status={status}, body=<{body}>"),
    )
}

/// A helper to create a non-retryable error.
pub(crate) fn non_retryable<T: Error + Send + Sync + 'static>(source: T) -> CredentialsError {
    CredentialsError::from_source(false, source)
}

pub(crate) fn non_retryable_from_str<T: Into<String>>(message: T) -> CredentialsError {
    CredentialsError::from_msg(false, message)
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::num::ParseIntError;

    #[test]
    fn helpers() {
        let e = super::non_retryable_from_str("test-only-err-123");
        assert!(!e.is_transient(), "{e}");
        let got = format!("{e}");
        assert!(got.contains("test-only-err-123"), "{got}");

        let input = "NaN".parse::<u32>().unwrap_err();
        let e = super::non_retryable(input.clone());
        assert!(!e.is_transient(), "{e:?}");
        let source = e.source().and_then(|e| e.downcast_ref::<ParseIntError>());
        assert!(matches!(source, Some(ParseIntError { .. })), "{e:?}");
    }
}
