// Copyright 2024 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// Code generated by sidekick. DO NOT EDIT.

use gax::error::{Error, HttpError};
use crate::{Credential, Result};

// Shared implementation across clients.
#[derive(Clone)]
struct InnerClient {
    http_client: reqwest::Client,
    cred: Credential,
    endpoint: String,
}

#[derive(serde::Serialize)]
#[allow(dead_code)]
struct NoBody {}

/// Stores sensitive data such as API keys, passwords, and certificates.
/// Provides convenience while improving security.
#[derive(Clone)]
pub struct SecretManagerService {
    inner: InnerClient,
}

impl std::fmt::Debug for SecretManagerService {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::result::Result<(), std::fmt::Error> {
        write!(f, "SecretManagerService[{}]", self.inner.endpoint)
    }
}

impl SecretManagerService {
    pub async fn new(conf: crate::ConfigBuilder) -> Result<Self> {
        let cred = conf
                .cred
                .unwrap_or(crate::ConfigBuilder::default_credential().await?); 
        let inner = InnerClient {
            http_client: conf.client.unwrap_or(crate::ConfigBuilder::default_client()),
            cred,
            endpoint: conf.endpoint.unwrap_or(crate::DEFAULT_HOST.to_string()),
        };
        Ok(Self { inner })
    }

    async fn fetch_token(&self) -> Result<String> {
        let tok = self
            .inner
            .cred
            .access_token()
            .await
            .map_err(Error::authentication)?;
        Ok(tok.value)
    }

    async fn execute<I: serde::ser::Serialize, O: serde::de::DeserializeOwned>(
        access_token: String,
        mut builder: reqwest::RequestBuilder,
        body: Option<I>,
    ) -> Result<O> {
        builder = builder.bearer_auth(access_token);
        if let Some(body) = body {
            builder = builder.json(&body);
        }
        let resp = builder.send().await.map_err(Error::io)?;
        if !resp.status().is_success() {
            let status = resp.status().as_u16();
            let headers = gax::error::convert_headers(resp.headers());
            let body = resp.bytes().await.map_err(Error::io)?;
            return Err(HttpError::new(status, headers, Some(body)).into());
        }
        let response = resp.json::<O>().await.map_err(Error::serde)?;
        Ok(response)
    }
}

impl crate::traits::SecretManagerService for SecretManagerService {
    /// Lists information about the supported locations for this service.
    async fn list_locations(&self, req: crate::model::ListLocationsRequest) -> Result<crate::model::ListLocationsResponse> {
        let builder = self.inner.http_client
            .get(format!(
               "{}/v1/projects/{}/locations",
               self.inner.endpoint,
               req.project,
            ))
            .query(&[("alt", "json")]);
        let builder = gax::query_parameter::add(builder, "filter", &req.filter).map_err(Error::other)?;
        let builder = gax::query_parameter::add(builder, "pageSize", &req.page_size).map_err(Error::other)?;
        let builder = gax::query_parameter::add(builder, "pageToken", &req.page_token).map_err(Error::other)?;
        let access_token = self.fetch_token().await?;
        Self::execute(access_token, builder, None::<NoBody>).await
    }

    /// Gets information about a location.
    async fn get_location(&self, req: crate::model::GetLocationRequest) -> Result<crate::model::Location> {
        let builder = self.inner.http_client
            .get(format!(
               "{}/v1/projects/{}/locations/{}",
               self.inner.endpoint,
               req.project,
               req.location,
            ))
            .query(&[("alt", "json")]);
        let access_token = self.fetch_token().await?;
        Self::execute(access_token, builder, None::<NoBody>).await
    }

    /// Lists Secrets.
    async fn list_secrets(&self, req: crate::model::ListSecretsRequest) -> Result<crate::model::ListSecretsResponse> {
        let builder = self.inner.http_client
            .get(format!(
               "{}/v1/projects/{}/secrets",
               self.inner.endpoint,
               req.project,
            ))
            .query(&[("alt", "json")]);
        let builder = gax::query_parameter::add(builder, "pageSize", &req.page_size).map_err(Error::other)?;
        let builder = gax::query_parameter::add(builder, "pageToken", &req.page_token).map_err(Error::other)?;
        let builder = gax::query_parameter::add(builder, "filter", &req.filter).map_err(Error::other)?;
        let access_token = self.fetch_token().await?;
        Self::execute(access_token, builder, None::<NoBody>).await
    }

    /// Creates a new Secret containing no SecretVersions.
    async fn create_secret(&self, req: crate::model::CreateSecretRequest) -> Result<crate::model::Secret> {
        let builder = self.inner.http_client
            .post(format!(
               "{}/v1/projects/{}/secrets",
               self.inner.endpoint,
               req.project,
            ))
            .query(&[("alt", "json")]);
        let builder = gax::query_parameter::add(builder, "secretId", &req.secret_id).map_err(Error::other)?;
        let access_token = self.fetch_token().await?;
        Self::execute(access_token, builder, Some(req.request_body)).await
    }

    /// Lists Secrets.
    async fn list_secrets_by_project_and_location(&self, req: crate::model::ListSecretsByProjectAndLocationRequest) -> Result<crate::model::ListSecretsResponse> {
        let builder = self.inner.http_client
            .get(format!(
               "{}/v1/projects/{}/locations/{}/secrets",
               self.inner.endpoint,
               req.project,
               req.location,
            ))
            .query(&[("alt", "json")]);
        let builder = gax::query_parameter::add(builder, "pageSize", &req.page_size).map_err(Error::other)?;
        let builder = gax::query_parameter::add(builder, "pageToken", &req.page_token).map_err(Error::other)?;
        let builder = gax::query_parameter::add(builder, "filter", &req.filter).map_err(Error::other)?;
        let access_token = self.fetch_token().await?;
        Self::execute(access_token, builder, None::<NoBody>).await
    }

    /// Creates a new Secret containing no SecretVersions.
    async fn create_secret_by_project_and_location(&self, req: crate::model::CreateSecretByProjectAndLocationRequest) -> Result<crate::model::Secret> {
        let builder = self.inner.http_client
            .post(format!(
               "{}/v1/projects/{}/locations/{}/secrets",
               self.inner.endpoint,
               req.project,
               req.location,
            ))
            .query(&[("alt", "json")]);
        let builder = gax::query_parameter::add(builder, "secretId", &req.secret_id).map_err(Error::other)?;
        let access_token = self.fetch_token().await?;
        Self::execute(access_token, builder, Some(req.request_body)).await
    }

    /// Creates a new SecretVersion containing secret data and attaches
    /// it to an existing Secret.
    async fn add_secret_version(&self, req: crate::model::AddSecretVersionRequest) -> Result<crate::model::SecretVersion> {
        let builder = self.inner.http_client
            .post(format!(
               "{}/v1/projects/{}/secrets/{}:addVersion",
               self.inner.endpoint,
               req.project,
               req.secret,
            ))
            .query(&[("alt", "json")]);
        let access_token = self.fetch_token().await?;
        Self::execute(access_token, builder, Some(req)).await
    }

    /// Creates a new SecretVersion containing secret data and attaches
    /// it to an existing Secret.
    async fn add_secret_version_by_project_and_location_and_secret(&self, req: crate::model::AddSecretVersionRequest) -> Result<crate::model::SecretVersion> {
        let builder = self.inner.http_client
            .post(format!(
               "{}/v1/projects/{}/locations/{}/secrets/{}:addVersion",
               self.inner.endpoint,
               req.project,
               req.location,
               req.secret,
            ))
            .query(&[("alt", "json")]);
        let access_token = self.fetch_token().await?;
        Self::execute(access_token, builder, Some(req)).await
    }

    /// Gets metadata for a given Secret.
    async fn get_secret(&self, req: crate::model::GetSecretRequest) -> Result<crate::model::Secret> {
        let builder = self.inner.http_client
            .get(format!(
               "{}/v1/projects/{}/secrets/{}",
               self.inner.endpoint,
               req.project,
               req.secret,
            ))
            .query(&[("alt", "json")]);
        let access_token = self.fetch_token().await?;
        Self::execute(access_token, builder, None::<NoBody>).await
    }

    /// Deletes a Secret.
    async fn delete_secret(&self, req: crate::model::DeleteSecretRequest) -> Result<crate::model::Empty> {
        let builder = self.inner.http_client
            .delete(format!(
               "{}/v1/projects/{}/secrets/{}",
               self.inner.endpoint,
               req.project,
               req.secret,
            ))
            .query(&[("alt", "json")]);
        let builder = gax::query_parameter::add(builder, "etag", &req.etag).map_err(Error::other)?;
        let access_token = self.fetch_token().await?;
        Self::execute(access_token, builder, None::<NoBody>).await
    }

    /// Updates metadata of an existing Secret.
    async fn update_secret(&self, req: crate::model::UpdateSecretRequest) -> Result<crate::model::Secret> {
        let builder = self.inner.http_client
            .patch(format!(
               "{}/v1/projects/{}/secrets/{}",
               self.inner.endpoint,
               req.project,
               req.secret,
            ))
            .query(&[("alt", "json")]);
        let builder = gax::query_parameter::add(builder, "updateMask", &serde_json::to_value(&req.update_mask).map_err(Error::serde)?).map_err(Error::other)?;
        let access_token = self.fetch_token().await?;
        Self::execute(access_token, builder, Some(req.request_body)).await
    }

    /// Gets metadata for a given Secret.
    async fn get_secret_by_project_and_location_and_secret(&self, req: crate::model::GetSecretByProjectAndLocationAndSecretRequest) -> Result<crate::model::Secret> {
        let builder = self.inner.http_client
            .get(format!(
               "{}/v1/projects/{}/locations/{}/secrets/{}",
               self.inner.endpoint,
               req.project,
               req.location,
               req.secret,
            ))
            .query(&[("alt", "json")]);
        let access_token = self.fetch_token().await?;
        Self::execute(access_token, builder, None::<NoBody>).await
    }

    /// Deletes a Secret.
    async fn delete_secret_by_project_and_location_and_secret(&self, req: crate::model::DeleteSecretByProjectAndLocationAndSecretRequest) -> Result<crate::model::Empty> {
        let builder = self.inner.http_client
            .delete(format!(
               "{}/v1/projects/{}/locations/{}/secrets/{}",
               self.inner.endpoint,
               req.project,
               req.location,
               req.secret,
            ))
            .query(&[("alt", "json")]);
        let builder = gax::query_parameter::add(builder, "etag", &req.etag).map_err(Error::other)?;
        let access_token = self.fetch_token().await?;
        Self::execute(access_token, builder, None::<NoBody>).await
    }

    /// Updates metadata of an existing Secret.
    async fn update_secret_by_project_and_location_and_secret(&self, req: crate::model::UpdateSecretByProjectAndLocationAndSecretRequest) -> Result<crate::model::Secret> {
        let builder = self.inner.http_client
            .patch(format!(
               "{}/v1/projects/{}/locations/{}/secrets/{}",
               self.inner.endpoint,
               req.project,
               req.location,
               req.secret,
            ))
            .query(&[("alt", "json")]);
        let builder = gax::query_parameter::add(builder, "updateMask", &serde_json::to_value(&req.update_mask).map_err(Error::serde)?).map_err(Error::other)?;
        let access_token = self.fetch_token().await?;
        Self::execute(access_token, builder, Some(req.request_body)).await
    }

    /// Lists SecretVersions. This call does not return secret
    /// data.
    async fn list_secret_versions(&self, req: crate::model::ListSecretVersionsRequest) -> Result<crate::model::ListSecretVersionsResponse> {
        let builder = self.inner.http_client
            .get(format!(
               "{}/v1/projects/{}/secrets/{}/versions",
               self.inner.endpoint,
               req.project,
               req.secret,
            ))
            .query(&[("alt", "json")]);
        let builder = gax::query_parameter::add(builder, "pageSize", &req.page_size).map_err(Error::other)?;
        let builder = gax::query_parameter::add(builder, "pageToken", &req.page_token).map_err(Error::other)?;
        let builder = gax::query_parameter::add(builder, "filter", &req.filter).map_err(Error::other)?;
        let access_token = self.fetch_token().await?;
        Self::execute(access_token, builder, None::<NoBody>).await
    }

    /// Lists SecretVersions. This call does not return secret
    /// data.
    async fn list_secret_versions_by_project_and_location_and_secret(&self, req: crate::model::ListSecretVersionsByProjectAndLocationAndSecretRequest) -> Result<crate::model::ListSecretVersionsResponse> {
        let builder = self.inner.http_client
            .get(format!(
               "{}/v1/projects/{}/locations/{}/secrets/{}/versions",
               self.inner.endpoint,
               req.project,
               req.location,
               req.secret,
            ))
            .query(&[("alt", "json")]);
        let builder = gax::query_parameter::add(builder, "pageSize", &req.page_size).map_err(Error::other)?;
        let builder = gax::query_parameter::add(builder, "pageToken", &req.page_token).map_err(Error::other)?;
        let builder = gax::query_parameter::add(builder, "filter", &req.filter).map_err(Error::other)?;
        let access_token = self.fetch_token().await?;
        Self::execute(access_token, builder, None::<NoBody>).await
    }

    /// Gets metadata for a SecretVersion.
    ///
    /// `projects/_*_/secrets/_*_/versions/latest` is an alias to the most recently
    /// created SecretVersion.
    async fn get_secret_version(&self, req: crate::model::GetSecretVersionRequest) -> Result<crate::model::SecretVersion> {
        let builder = self.inner.http_client
            .get(format!(
               "{}/v1/projects/{}/secrets/{}/versions/{}",
               self.inner.endpoint,
               req.project,
               req.secret,
               req.version,
            ))
            .query(&[("alt", "json")]);
        let access_token = self.fetch_token().await?;
        Self::execute(access_token, builder, None::<NoBody>).await
    }

    /// Gets metadata for a SecretVersion.
    ///
    /// `projects/_*_/secrets/_*_/versions/latest` is an alias to the most recently
    /// created SecretVersion.
    async fn get_secret_version_by_project_and_location_and_secret_and_version(&self, req: crate::model::GetSecretVersionByProjectAndLocationAndSecretAndVersionRequest) -> Result<crate::model::SecretVersion> {
        let builder = self.inner.http_client
            .get(format!(
               "{}/v1/projects/{}/locations/{}/secrets/{}/versions/{}",
               self.inner.endpoint,
               req.project,
               req.location,
               req.secret,
               req.version,
            ))
            .query(&[("alt", "json")]);
        let access_token = self.fetch_token().await?;
        Self::execute(access_token, builder, None::<NoBody>).await
    }

    /// Accesses a SecretVersion. This call returns the secret data.
    ///
    /// `projects/_*_/secrets/_*_/versions/latest` is an alias to the most recently
    /// created SecretVersion.
    async fn access_secret_version(&self, req: crate::model::AccessSecretVersionRequest) -> Result<crate::model::AccessSecretVersionResponse> {
        let builder = self.inner.http_client
            .get(format!(
               "{}/v1/projects/{}/secrets/{}/versions/{}:access",
               self.inner.endpoint,
               req.project,
               req.secret,
               req.version,
            ))
            .query(&[("alt", "json")]);
        let access_token = self.fetch_token().await?;
        Self::execute(access_token, builder, None::<NoBody>).await
    }

    /// Accesses a SecretVersion. This call returns the secret data.
    ///
    /// `projects/_*_/secrets/_*_/versions/latest` is an alias to the most recently
    /// created SecretVersion.
    async fn access_secret_version_by_project_and_location_and_secret_and_version(&self, req: crate::model::AccessSecretVersionByProjectAndLocationAndSecretAndVersionRequest) -> Result<crate::model::AccessSecretVersionResponse> {
        let builder = self.inner.http_client
            .get(format!(
               "{}/v1/projects/{}/locations/{}/secrets/{}/versions/{}:access",
               self.inner.endpoint,
               req.project,
               req.location,
               req.secret,
               req.version,
            ))
            .query(&[("alt", "json")]);
        let access_token = self.fetch_token().await?;
        Self::execute(access_token, builder, None::<NoBody>).await
    }

    /// Disables a SecretVersion.
    ///
    /// Sets the state of the SecretVersion to
    /// DISABLED.
    async fn disable_secret_version(&self, req: crate::model::DisableSecretVersionRequest) -> Result<crate::model::SecretVersion> {
        let builder = self.inner.http_client
            .post(format!(
               "{}/v1/projects/{}/secrets/{}/versions/{}:disable",
               self.inner.endpoint,
               req.project,
               req.secret,
               req.version,
            ))
            .query(&[("alt", "json")]);
        let access_token = self.fetch_token().await?;
        Self::execute(access_token, builder, Some(req)).await
    }

    /// Disables a SecretVersion.
    ///
    /// Sets the state of the SecretVersion to
    /// DISABLED.
    async fn disable_secret_version_by_project_and_location_and_secret_and_version(&self, req: crate::model::DisableSecretVersionRequest) -> Result<crate::model::SecretVersion> {
        let builder = self.inner.http_client
            .post(format!(
               "{}/v1/projects/{}/locations/{}/secrets/{}/versions/{}:disable",
               self.inner.endpoint,
               req.project,
               req.location,
               req.secret,
               req.version,
            ))
            .query(&[("alt", "json")]);
        let access_token = self.fetch_token().await?;
        Self::execute(access_token, builder, Some(req)).await
    }

    /// Enables a SecretVersion.
    ///
    /// Sets the state of the SecretVersion to
    /// ENABLED.
    async fn enable_secret_version(&self, req: crate::model::EnableSecretVersionRequest) -> Result<crate::model::SecretVersion> {
        let builder = self.inner.http_client
            .post(format!(
               "{}/v1/projects/{}/secrets/{}/versions/{}:enable",
               self.inner.endpoint,
               req.project,
               req.secret,
               req.version,
            ))
            .query(&[("alt", "json")]);
        let access_token = self.fetch_token().await?;
        Self::execute(access_token, builder, Some(req)).await
    }

    /// Enables a SecretVersion.
    ///
    /// Sets the state of the SecretVersion to
    /// ENABLED.
    async fn enable_secret_version_by_project_and_location_and_secret_and_version(&self, req: crate::model::EnableSecretVersionRequest) -> Result<crate::model::SecretVersion> {
        let builder = self.inner.http_client
            .post(format!(
               "{}/v1/projects/{}/locations/{}/secrets/{}/versions/{}:enable",
               self.inner.endpoint,
               req.project,
               req.location,
               req.secret,
               req.version,
            ))
            .query(&[("alt", "json")]);
        let access_token = self.fetch_token().await?;
        Self::execute(access_token, builder, Some(req)).await
    }

    /// Destroys a SecretVersion.
    ///
    /// Sets the state of the SecretVersion to
    /// DESTROYED and irrevocably destroys the
    /// secret data.
    async fn destroy_secret_version(&self, req: crate::model::DestroySecretVersionRequest) -> Result<crate::model::SecretVersion> {
        let builder = self.inner.http_client
            .post(format!(
               "{}/v1/projects/{}/secrets/{}/versions/{}:destroy",
               self.inner.endpoint,
               req.project,
               req.secret,
               req.version,
            ))
            .query(&[("alt", "json")]);
        let access_token = self.fetch_token().await?;
        Self::execute(access_token, builder, Some(req)).await
    }

    /// Destroys a SecretVersion.
    ///
    /// Sets the state of the SecretVersion to
    /// DESTROYED and irrevocably destroys the
    /// secret data.
    async fn destroy_secret_version_by_project_and_location_and_secret_and_version(&self, req: crate::model::DestroySecretVersionRequest) -> Result<crate::model::SecretVersion> {
        let builder = self.inner.http_client
            .post(format!(
               "{}/v1/projects/{}/locations/{}/secrets/{}/versions/{}:destroy",
               self.inner.endpoint,
               req.project,
               req.location,
               req.secret,
               req.version,
            ))
            .query(&[("alt", "json")]);
        let access_token = self.fetch_token().await?;
        Self::execute(access_token, builder, Some(req)).await
    }

    /// Sets the access control policy on the specified secret. Replaces any
    /// existing policy.
    ///
    /// Permissions on SecretVersions are enforced according
    /// to the policy set on the associated Secret.
    async fn set_iam_policy(&self, req: crate::model::SetIamPolicyRequest) -> Result<crate::model::Policy> {
        let builder = self.inner.http_client
            .post(format!(
               "{}/v1/projects/{}/secrets/{}:setIamPolicy",
               self.inner.endpoint,
               req.project,
               req.secret,
            ))
            .query(&[("alt", "json")]);
        let access_token = self.fetch_token().await?;
        Self::execute(access_token, builder, Some(req)).await
    }

    /// Sets the access control policy on the specified secret. Replaces any
    /// existing policy.
    ///
    /// Permissions on SecretVersions are enforced according
    /// to the policy set on the associated Secret.
    async fn set_iam_policy_by_project_and_location_and_secret(&self, req: crate::model::SetIamPolicyRequest) -> Result<crate::model::Policy> {
        let builder = self.inner.http_client
            .post(format!(
               "{}/v1/projects/{}/locations/{}/secrets/{}:setIamPolicy",
               self.inner.endpoint,
               req.project,
               req.location,
               req.secret,
            ))
            .query(&[("alt", "json")]);
        let access_token = self.fetch_token().await?;
        Self::execute(access_token, builder, Some(req)).await
    }

    /// Gets the access control policy for a secret.
    /// Returns empty policy if the secret exists and does not have a policy set.
    async fn get_iam_policy(&self, req: crate::model::GetIamPolicyRequest) -> Result<crate::model::Policy> {
        let builder = self.inner.http_client
            .get(format!(
               "{}/v1/projects/{}/secrets/{}:getIamPolicy",
               self.inner.endpoint,
               req.project,
               req.secret,
            ))
            .query(&[("alt", "json")]);
        let builder = gax::query_parameter::add(builder, "options.requestedPolicyVersion", &req.options_requested_policy_version).map_err(Error::other)?;
        let access_token = self.fetch_token().await?;
        Self::execute(access_token, builder, None::<NoBody>).await
    }

    /// Gets the access control policy for a secret.
    /// Returns empty policy if the secret exists and does not have a policy set.
    async fn get_iam_policy_by_project_and_location_and_secret(&self, req: crate::model::GetIamPolicyByProjectAndLocationAndSecretRequest) -> Result<crate::model::Policy> {
        let builder = self.inner.http_client
            .get(format!(
               "{}/v1/projects/{}/locations/{}/secrets/{}:getIamPolicy",
               self.inner.endpoint,
               req.project,
               req.location,
               req.secret,
            ))
            .query(&[("alt", "json")]);
        let builder = gax::query_parameter::add(builder, "options.requestedPolicyVersion", &req.options_requested_policy_version).map_err(Error::other)?;
        let access_token = self.fetch_token().await?;
        Self::execute(access_token, builder, None::<NoBody>).await
    }

    /// Returns permissions that a caller has for the specified secret.
    /// If the secret does not exist, this call returns an empty set of
    /// permissions, not a NOT_FOUND error.
    ///
    /// Note: This operation is designed to be used for building permission-aware
    /// UIs and command-line tools, not for authorization checking. This operation
    /// may "fail open" without warning.
    async fn test_iam_permissions(&self, req: crate::model::TestIamPermissionsRequest) -> Result<crate::model::TestIamPermissionsResponse> {
        let builder = self.inner.http_client
            .post(format!(
               "{}/v1/projects/{}/secrets/{}:testIamPermissions",
               self.inner.endpoint,
               req.project,
               req.secret,
            ))
            .query(&[("alt", "json")]);
        let access_token = self.fetch_token().await?;
        Self::execute(access_token, builder, Some(req)).await
    }

    /// Returns permissions that a caller has for the specified secret.
    /// If the secret does not exist, this call returns an empty set of
    /// permissions, not a NOT_FOUND error.
    ///
    /// Note: This operation is designed to be used for building permission-aware
    /// UIs and command-line tools, not for authorization checking. This operation
    /// may "fail open" without warning.
    async fn test_iam_permissions_by_project_and_location_and_secret(&self, req: crate::model::TestIamPermissionsRequest) -> Result<crate::model::TestIamPermissionsResponse> {
        let builder = self.inner.http_client
            .post(format!(
               "{}/v1/projects/{}/locations/{}/secrets/{}:testIamPermissions",
               self.inner.endpoint,
               req.project,
               req.location,
               req.secret,
            ))
            .query(&[("alt", "json")]);
        let access_token = self.fetch_token().await?;
        Self::execute(access_token, builder, Some(req)).await
    }

}

