# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

[general]
language             = 'rust'
specification-source = 'google/storage/v2'

[source]
skipped-ids = """\
    .google.storage.v2.BidiReadHandle,\
    .google.storage.v2.BidiReadObjectError,\
    .google.storage.v2.BidiReadObjectRedirectedError,\
    .google.storage.v2.BidiReadObjectRequest,\
    .google.storage.v2.BidiReadObjectResponse,\
    .google.storage.v2.BidiReadObjectSpec,\
    .google.storage.v2.BidiWriteHandle,\
    .google.storage.v2.BidiWriteObjectRedirectedError,\
    .google.storage.v2.BidiWriteObjectRequest,\
    .google.storage.v2.BidiWriteObjectRequest.FirstMessage,\
    .google.storage.v2.BidiWriteObjectResponse,\
    .google.storage.v2.ChecksummedData,\
    .google.storage.v2.CancelResumableWriteRequest,\
    .google.storage.v2.CancelResumableWriteResponse,\
    .google.storage.v2.ObjectRangeData,\
    .google.storage.v2.QueryWriteStatusRequest,\
    .google.storage.v2.QueryWriteStatusResponse,\
    .google.storage.v2.ReadObjectRequest,\
    .google.storage.v2.ReadObjectResponse,\
    .google.storage.v2.ReadRange,\
    .google.storage.v2.ReadRangeError,\
    .google.storage.v2.StartResumableWriteRequest,\
    .google.storage.v2.StartResumableWriteResponse,\
    .google.storage.v2.WriteObjectRequest,\
    .google.storage.v2.WriteObjectResponse,\
    .google.storage.v2.WriteObjectSpec,\
    .google.storage.v2.AppendObjectSpec,\
    """

[codec]
copyright-year    = '2025'
template-override = 'templates/convert-prost'
module-path       = 'crate::generated::gapic::model'
